# Generated by Django 4.1.6 on 2023-02-24 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('itemID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('itemCategory', models.CharField(max_length=100)),
                ('itemDescription', models.TextField()),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=320)),
                ('userMobile', models.CharField(max_length=11)),
                ('password1', models.TextField()),
                ('password2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('forum', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuition.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemQuantity', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuition.itemmenu')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuition.user')),
            ],
        ),
    ]
