# Generated by Django 4.1.6 on 2023-02-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
