# Generated by Django 4.1.6 on 2023-02-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Not Ready', max_length=10),
        ),
    ]
