# Generated by Django 5.0.7 on 2024-10-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0003_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemMenu',
            new_name='TuitionPackage',
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemQuantity', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('status', models.CharField(default='Not Ready', max_length=10)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('tuitionPackageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuition.tuitionpackage')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuition.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
