# Generated by Django 5.0.7 on 2024-10-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0004_rename_itemmenu_tuitionpackage_registration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionpackage',
            old_name='itemPrice',
            new_name='totalPrice',
        ),
        migrations.RenameField(
            model_name='tuitionpackage',
            old_name='itemCategory',
            new_name='tuitionCategory',
        ),
        migrations.RenameField(
            model_name='tuitionpackage',
            old_name='itemDescription',
            new_name='tuitionDescription',
        ),
        migrations.RenameField(
            model_name='tuitionpackage',
            old_name='itemID',
            new_name='tuitionID',
        ),
    ]
