# Generated by Django 5.0.7 on 2024-10-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0006_rename_tuitioncategory_tuitionpackage_itemcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionpackage',
            old_name='itemID',
            new_name='tuitionPackageID',
        ),
    ]
