# Generated by Django 5.0.7 on 2024-10-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0007_rename_itemid_tuitionpackage_tuitionpackageid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionpackage',
            old_name='itemCategory',
            new_name='packageCategory',
        ),
        migrations.RenameField(
            model_name='tuitionpackage',
            old_name='itemDescription',
            new_name='packageDescription',
        ),
        migrations.RenameField(
            model_name='tuitionpackage',
            old_name='itemPrice',
            new_name='packagePrice',
        ),
    ]
