# Generated by Django 5.0.7 on 2024-10-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0008_rename_itemcategory_tuitionpackage_packagecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='session',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
