# Generated by Django 5.0.7 on 2024-10-20 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0009_registration_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionpackage',
            name='suubjects',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='tuitionpackage',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tuition.user'),
        ),
    ]
