# Generated by Django 5.0.7 on 2024-10-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0010_tuitionpackage_suubjects_tuitionpackage_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionpackage',
            old_name='suubjects',
            new_name='subjects',
        ),
    ]
