# Generated by Django 5.0.7 on 2024-10-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0011_rename_suubjects_tuitionpackage_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionpackage',
            name='subjects',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
