# Generated by Django 5.0.7 on 2024-10-20 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0013_alter_tuitionpackage_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionpackage',
            name='userID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Tuition.user'),
        ),
    ]
