# Generated by Django 5.0.7 on 2024-10-20 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0014_alter_tuitionpackage_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionpackage',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuition.user'),
        ),
    ]
