# Generated by Django 5.0.7 on 2024-10-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0015_alter_tuitionpackage_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='session',
            field=models.CharField(max_length=10),
        ),
    ]
