# Generated by Django 5.0.7 on 2024-10-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0016_alter_registration_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='tuitionPackageID',
        ),
        migrations.AddField(
            model_name='registration',
            name='registrationID',
            field=models.CharField(default='', max_length=6, primary_key=True, serialize=False),
        ),
    ]
