# Generated by Django 5.0.7 on 2024-10-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0017_remove_registration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registrationID',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
