# Generated by Django 5.0.7 on 2024-10-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0018_alter_registration_registrationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='itemQuantity',
        ),
        migrations.AddField(
            model_name='registration',
            name='registrationPlace',
            field=models.TextField(default=None),
        ),
    ]
