# Generated by Django 5.0.7 on 2024-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0019_remove_registration_itemquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registrationPlace',
            field=models.TextField(),
        ),
    ]
