# Generated by Django 5.0.7 on 2024-10-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0020_alter_registration_registrationplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='timeStamp',
            new_name='time',
        ),
    ]
