# Generated by Django 5.0.7 on 2024-10-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tuition', '0021_rename_timestamp_registration_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='totalPrice',
            new_name='registrationPrice',
        ),
    ]
